name: Horusec Analysis

on:
  push:
    branches:
        - main

jobs:
    horusec:
        name: Horusec Analysis
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Set up Node.js
            uses: actions/setup-node@v3
            with:
              node-version: '18' # Adjust to your project's Node.js version

          - name: Install dependencies
            run: npm install

          - name: Install Horusec CLI
            run: curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest

        #   - name: Run Horusec analysis
        #     run: horusec start -p .

        #   - name: Upload Horusec report as an artifact
        #     uses: actions/upload-artifact@v3
        #     with:
        #       name: horusec-report
        #       path: .horusec/horusec-result.json

    checking_code:
        name: Horusec Scan
        runs-on: ubuntu-latest
        
        steps:
        - name: Run Horusec
          id: run_horusec
          uses: fike/horusec-action@v0.1
          with:
            arguments: --config-file-path=horusec-config.json

                